// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(PromiPointsDbContext))]
    partial class PromiPointsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Business.Entities.MonthlyAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("PointsReceived")
                        .HasColumnType("int");

                    b.Property<int>("PointsRemaining")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Month")
                        .IsUnique();

                    b.ToTable("MonthlyAllocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Month = "2026-02",
                            PointsReceived = 5,
                            PointsRemaining = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Month = "2026-02",
                            PointsReceived = 4,
                            PointsRemaining = 6,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Month = "2026-02",
                            PointsReceived = 0,
                            PointsRemaining = 10,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Month = "2026-02",
                            PointsReceived = 2,
                            PointsRemaining = 8,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Month = "2026-02",
                            PointsReceived = 0,
                            PointsRemaining = 6,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Month = "2026-02",
                            PointsReceived = 0,
                            PointsRemaining = 10,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Month = "2026-02",
                            PointsReceived = 0,
                            PointsRemaining = 10,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Month = "2026-02",
                            PointsReceived = 0,
                            PointsRemaining = 10,
                            UserId = 8
                        });
                });

            modelBuilder.Entity("Business.Entities.PointAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FromUserId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("ToUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("PointAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Trabajo en equipo",
                            FromUserId = 2,
                            Message = "¡Excelente colaboración en el proyecto!",
                            Month = "2026-02",
                            Points = 3,
                            Timestamp = 1740268800000L,
                            ToUserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Innovación",
                            FromUserId = 4,
                            Message = "Gran idea para mejorar el proceso",
                            Month = "2026-02",
                            Points = 2,
                            Timestamp = 1739836800000L,
                            ToUserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Liderazgo",
                            FromUserId = 5,
                            Month = "2026-02",
                            Points = 4,
                            Timestamp = 1740096000000L,
                            ToUserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Category = "Colaboración",
                            FromUserId = 1,
                            Message = "Siempre dispuesto a ayudar",
                            Month = "2026-02",
                            Points = 2,
                            Timestamp = 1740355200000L,
                            ToUserId = 4
                        });
                });

            modelBuilder.Entity("Business.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Desarrollo",
                            Email = "maria.garcia@grupoprominente.com",
                            Name = "María García",
                            PasswordHash = "$2a$11$hyOlTRGeP6zgPX2cZ4WwVOayoO9WOg/E.0hDp.l03bVeqKs4sNhGa",
                            Role = "employee"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Email = "juan.perez@grupoprominente.com",
                            Name = "Juan Pérez",
                            PasswordHash = "$2a$11$hyOlTRGeP6zgPX2cZ4WwVOayoO9WOg/E.0hDp.l03bVeqKs4sNhGa",
                            Role = "employee"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "People & Culture",
                            Email = "ana.rodriguez@grupoprominente.com",
                            Name = "Ana Rodríguez",
                            PasswordHash = "$2a$11$hyOlTRGeP6zgPX2cZ4WwVOayoO9WOg/E.0hDp.l03bVeqKs4sNhGa",
                            Role = "people"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Ventas",
                            Email = "carlos.lopez@grupoprominente.com",
                            Name = "Carlos López",
                            PasswordHash = "$2a$11$hyOlTRGeP6zgPX2cZ4WwVOayoO9WOg/E.0hDp.l03bVeqKs4sNhGa",
                            Role = "employee"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Desarrollo",
                            Email = "laura.martinez@grupoprominente.com",
                            Name = "Laura Martínez",
                            PasswordHash = "$2a$11$hyOlTRGeP6zgPX2cZ4WwVOayoO9WOg/E.0hDp.l03bVeqKs4sNhGa",
                            Role = "employee"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operaciones",
                            Email = "diego.sanchez@grupoprominente.com",
                            Name = "Diego Sánchez",
                            PasswordHash = "$2a$11$hyOlTRGeP6zgPX2cZ4WwVOayoO9WOg/E.0hDp.l03bVeqKs4sNhGa",
                            Role = "employee"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Email = "sofia.torres@grupoprominente.com",
                            Name = "Sofia Torres",
                            PasswordHash = "$2a$11$hyOlTRGeP6zgPX2cZ4WwVOayoO9WOg/E.0hDp.l03bVeqKs4sNhGa",
                            Role = "employee"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Ventas",
                            Email = "roberto.flores@grupoprominente.com",
                            Name = "Roberto Flores",
                            PasswordHash = "$2a$11$hyOlTRGeP6zgPX2cZ4WwVOayoO9WOg/E.0hDp.l03bVeqKs4sNhGa",
                            Role = "employee"
                        });
                });

            modelBuilder.Entity("Business.Entities.MonthlyAllocation", b =>
                {
                    b.HasOne("Business.Entities.User", "User")
                        .WithMany("Allocations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Business.Entities.PointAssignment", b =>
                {
                    b.HasOne("Business.Entities.User", "FromUser")
                        .WithMany("SentAssignments")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Business.Entities.User", "ToUser")
                        .WithMany("ReceivedAssignments")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Business.Entities.User", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("ReceivedAssignments");

                    b.Navigation("SentAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
